"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var BurgerMenu_1 = require("./BurgerMenu/BurgerMenu");
Object.defineProperty(exports, "BurgerMenu", { enumerable: true, get: function () { return BurgerMenu_1.default; } });
var Github_1 = require("./Github/Github");
Object.defineProperty(exports, "Github", { enumerable: true, get: function () { return Github_1.default; } });
var Linkedin_1 = require("./Linkedin/Linkedin");
Object.defineProperty(exports, "Linkedin", { enumerable: true, get: function () { return Linkedin_1.default; } });
var GraduationCap_1 = require("./GraduationCap/GraduationCap");
Object.defineProperty(exports, "GraduationCap", { enumerable: true, get: function () { return GraduationCap_1.default; } });
var Suitcase_1 = require("./Suitcase/Suitcase");
Object.defineProperty(exports, "Suitcase", { enumerable: true, get: function () { return Suitcase_1.default; } });
var Search_1 = require("./Search/Search");
Object.defineProperty(exports, "Search", { enumerable: true, get: function () { return Search_1.default; } });
var EmptyBox_1 = require("./EmptyBox/EmptyBox");
Object.defineProperty(exports, "EmptyBox", { enumerable: true, get: function () { return EmptyBox_1.default; } });
var Download_1 = require("./DownloadIcon/Download");
Object.defineProperty(exports, "Download", { enumerable: true, get: function () { return Download_1.default; } });
var Code_1 = require("./Code/Code");
Object.defineProperty(exports, "Code", { enumerable: true, get: function () { return Code_1.default; } });
var Trash_1 = require("./Trash/Trash");
Object.defineProperty(exports, "Trash", { enumerable: true, get: function () { return Trash_1.default; } });
var WorldWideWeb_1 = require("./WorldWideWeb/WorldWideWeb");
Object.defineProperty(exports, "WorldWideWeb", { enumerable: true, get: function () { return WorldWideWeb_1.default; } });
//# sourceMappingURL=index.js.map